server:
  port: 8081
  servlet:
    context-path: /api/v1/user
  
spring:
  application:
    name: user-ms-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Swamy786@
    url: jdbc:mysql://localhost:3306/no_name_app
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      
#debug: true
