server:
  port: 8081
  servlet:
    context-path: /api/v1/user
  
spring:
  application:
    name: user-ms-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Swamy786@
    url: jdbc:mysql://localhost:3306/no_name_app
    username: root
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com          # SMTP server host
    port: 587                     # SMTP server port
    username: creatorbhargav000@gmail.com  # Your Gmail email address
    password: uzmmzxjsvlyfkgsw        # Your Gmail password or app-specific password
    properties:
      mail:
        smtp:
          auth: true               # Enable SMTP authentication
          starttls:
            enable: true           # Enable STARTTLS encryption
          
      
#debug: true
